version: '3.4'

services:
  host.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ReverseProxy__Clusters__blogsCluster__Destinations__destination1__Address=http://modules.blog
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./.containers/logs:/logs
  modules.blog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - BaseUrl=http://localhost
    # ports:
    #   - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./.containers/logs:/logs

  # sqlserver:
  #   volumes:
  #     - ./.containers/mssql:/var/opt/mssql/data
  # elasticsearch:
  #   volumes:
  #     - ./.containers/elasticsearch-data:/usr/share/elasticsearch/data
  # kibana:
  #   volumes:
  #     - ./.containers/kibana:/usr/share/kibana/data