version: '3.4'

services:
  host.web:
    image: ${DOCKER_REGISTRY-}hostweb
    build:
      context: .
      dockerfile: Host.Web/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql_server_container
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

  
