version: '3.4'

services:
  host.web:
    container_name: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ReverseProxy__Clusters__blogsCluster__Destinations__destination1__Address=http://modules.blog
      - IdentityUser__Password=Root!234
    ports:
      - 80
    volumes:
      - ./.containers/${ENVIRONMENT}/db:/app/db
  modules.blog:
    container_name: modules.blog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - BaseUrl=http://localhost
    volumes:
      - ./.containers/${ENVIRONMENT}/db:/app/db

  # sqlserver:
  #   volumes:
  #     - ./.containers/mssql:/var/opt/mssql/data
  # elasticsearch:
  #   volumes:
  #     - ./.containers/elasticsearch-data:/usr/share/elasticsearch/data
  # kibana:
  #   volumes:
  #     - ./.containers/kibana:/usr/share/kibana/data